[package]
name = "mangatan"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
embed-jre = []

[dependencies]
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
directories.workspace = true
eframe.workspace = true
futures.workspace = true
futures-util.workspace = true
image.workspace = true
mime_guess.workspace = true
open.workspace = true
reqwest.workspace = true
rust-embed.workspace = true
serde.workspace = true
self_update.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zip.workspace = true

# Internal Crates
mangatan-ocr-server.workspace = true
mangatan-yomitan-server.workspace = true
mangatan-anki-server.workspace = true

[build-dependencies]
vergen = { version = "9.0", features = ["build", "cargo", "emit_and_set", "rustc"] }
vergen-git2 = "1.0"

[lints]
workspace = true
