[package]
name = "mangatan_android"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
autobins = false 

[package.metadata.android]
package = "com.mangatan.app"
label = "Mangatan"
min_sdk_version = 23
target_sdk_version = 28 
build_targets = ["aarch64-linux-android"]
assets = "assets"

[[package.metadata.android.uses_permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.uses_permission]]
name = "android.permission.ACCESS_NETWORK_STATE"

[package.metadata.android.application]
allow_native_heap_pointer_tagging = false
request_legacy_external_storage = true

[lib]
crate-type = ["cdylib"]

[target.'cfg(target_os = "android")'.dependencies]
# GUI
eframe = { version = "0.29", default-features = false, features = ["wgpu", "android-native-activity" ] }
egui = "0.29"
winit = "0.30"

# Web Server & Networking
# IMPORTANT: reqwest 0.12 uses http 1.0, matching axum 0.7
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "stream"] }
axum = { version = "0.8.7", features = ["macros", "multipart", "ws"] }
tower-http = { version = "0.5", features = ["cors", "fs", "trace"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
mime_guess = "2"

# WebSockets
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] }

# System
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.2"
libc = "0.2"
jni = "0.21"
libloading = "0.8"
tar = "0.4"
lazy_static = "1.4"
mangatan-ocr-server.workspace = true
openssl = { version = "0.10", features = ["vendored"] }

android-activity = { version = "0.6", features = ["native-activity"] }
