name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-udeps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Install NASM
      uses: ilammy/setup-nasm@v1

    - name: Install cargo udeps
      run: cargo install cargo-udeps --locked

    - name: Run cargo udeps
      run: cargo +nightly udeps --workspace --tests --all-targets --release --exclude ef-tests
  
  cargo-workspace-lints:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true        

    - name: Install cargo workspace lints
      run: cargo install cargo-workspace-lints --locked

    - name: Run cargo workspace lints
      run: cargo workspace-lints
